rails-version/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "job#index", as: "root"
  get "/job-manager/:job_id", to: "job#job_manager", as: "manager"
  get "/job-manager/:job_id/candidate/:candidate_id", to: "job#job_manager", as: "candidate"

  get "/new-job", to: "job#new", as: "new_job"
  get "/new-candidate", to: "candidate#new", as: "new_candidate"

  post "/new-candidate", to: "candidate#create", as: "create_candidate"
  post "/new-job", to: "job#create", as: "create_job"

  get "/progress-candidate", to: "candidate#progress", as: "progress_candidate"
  get "/disqualify-candidate", to: "candidate#disqualify", as: "disqualify_candidate"
  get "/edit-candidate/:candidate_id", to: "candidate#edit", as: "edit_candidate"

  patch "/job-manager/:job_id/candidate/:candidate_id", to: "candidate#update"

  get "/new-note/candidate/:candidate_id", to: "note#new", as: "new_note"
  post "/new-note/candidate/:candidate_id", to: "note#create"

  get "/new-interview/candidate/:candidate_id", to: "interview#new", as: "new_interview"
  post "/new-interview/candidate/:candidate_id", to: "interview#create"

  get "/job-manager/:job_id/interviews", to: "interview#show", as: "interview_list"

  get "/complete-interview/candidate/:candidate_id", to: "interview#complete"
  patch "/complete-interview/candidate/:candidate_id", to: "interview#complete", as: "complete_interview"

  get "/reschedule-interview/candidate/:candidate_id", to: "interview#reschedule", as: "reschedule_interview"
  patch "/reschedule-interview/candidate/:candidate_id", to: "interview#update", as: "update_reschedule"


end

rails-version/app/models/candidate.rb
class Candidate < ApplicationRecord
end

rails-version/app/controllers/candidate_controller.rb
class CandidateController < ApplicationController

    def new
        @candidate = Candidate.new
    end

    def create
        @candidate = Candidate.new(candidate_params)
        @candidate.status = "applied"

        if @candidate.save
            redirect_to manager_path(@candidate[:job_id])
        else
            render "new"
        end
    end

    def progress
        stage = ["applied", "contacted", "screened", "shortlisted", "interview", "offer", "accepted", "disqualified"]
        @candidate = Candidate.find(params[:candidate_id])

        if @candidate[:status] == "accepted"
            @prog_error = "Can't progress further."
            redirect_to candidate_path(:job_id => @candidate[:job_id].to_i,:candidate_id => @candidate[:id], :prog_error => @prog_error)
        elsif @candidate[:status] == "disqualified"
            @prog_error = "#{@candidate[:first_name]} #{@candidate[:last_name]} has been disqualified."
            redirect_to candidate_path(:job_id => @candidate[:job_id].to_i,:candidate_id => @candidate[:id], :prog_error => @prog_error)
        else
            @candidate.update(status: stage[stage.index(@candidate.status)+1])

            @note = Note.new
            @note.candidate_id = params[:candidate_id]
            @note.note = "Progressed to #{stage[stage.index(@candidate.status)]}"
            @note.save

            if @candidate.save
                redirect_to candidate_path(:job_id => @candidate[:job_id].to_i,:candidate_id => @candidate[:id], :prog_error => @prog_error)
            else
                render "new"
            end
        end

    end

    def disqualify
        
        @candidate = Candidate.find(params[:candidate_id])
        if @candidate[:status] == "disqualified"
            @prog_error = "#{@candidate[:first_name]} #{@candidate[:last_name]} is already disqualified."
            redirect_to candidate_path(:job_id => @candidate[:job_id].to_i,:candidate_id => @candidate[:id], :prog_error => @prog_error)
        else
            @candidate.update(status: "disqualified")
    
            @note = Note.new
            @note.candidate_id = params[:candidate_id]
            @note.note = "Disqualified"
            @note.save
    
            if @candidate.save
                redirect_to candidate_path(:job_id => @candidate[:job_id].to_i,:candidate_id => @candidate[:id], :prog_error => @prog_error)
            else
                render "new"
            end
        end

    end

    def edit 
        @candidate = Candidate.find(params[:candidate_id])
    end

    def update
        candidate = Candidate.find(params[:candidate_id])
        candidate.update(candidate_params)
        if candidate.valid? && candidate.save
            redirect_to candidate_path(:job_id => candidate[:job_id].to_i, :candidate_id => candidate[:id])
        else
            render "edit"
        end
    end

    private
    def candidate_params
        params.require(:candidate).permit(:job_id, :first_name, :last_name, :occupation, :email, :number, :status)
    end

end

rails-version/app/helpers/candidate_helper.rb
module CandidateHelper
end

rails-version/app/views/candidate/edit.html.erb
<div class ="add-form">
    <h1> Edit Details</h1>
    <p> Please change details below, and press save to save all changes </p>

    <%=form_with model:@candidate, class: "form-class" do |form| %>
        <%= label(:job_id,"Job ID")%> <br>
        <%= form.text_field :job_id %> <br><br>

        <%= label(:first_name,"First Name")%> <br>
        <%= form.text_field :first_name %><br><br>

        <%= label(:last_name,"Last Name")%><br>
        <%= form.text_field :last_name %> <br><br>

        <%= label(:status,"Status")%><br>
        <%= form.select(:status, ['applied', 'contacted', 'screened', 'shortlisted', 'interview', 'offer', 'accepted', 'disqualified'] )  %><br><br>

        <%= label(:occupation,"Occupation")%><br>
        <%= form.text_field :occupation %> <br><br>

        <%= label(:email,"Email")%> <br>
        <%= form.email_field :email %> <br><br>

        <%= label(:number,"Contact Number")%> <br>
        <%= form.text_field :number %> <br><br>

        <%= label(:address,"Address")%> <br>
        <%= form.text_field :address %> <br><br>
        <%= form.submit "Save Changes", class: "button-class" %>


    <%end%>
</div>

rails-version/app/views/candidate/new.html.erb
<div class ="add-form">
    <h1> Add Candidate </h1>
    <p> Please complete all fields </p>

    <%=form_with model:@candidate, url: create_candidate_path() do |form| %>
        <%= label(:job_id,"Job ID")%> <br>
        <%= form.number_field :job_id %> <br><br>

        <%= label(:first_name,"First Name")%> <br>
        <%= form.text_field :first_name %><br><br>

        <%= label(:last_name,"Last Name")%><br>
        <%= form.text_field :last_name %> <br><br>

        <%= label(:occupation,"Occupation")%><br>
        <%= form.text_field :occupation %> <br><br>

        <%= label(:email,"Email")%> <br>
        <%= form.email_field :email %> <br><br>

        <%= label(:number,"Contact Number")%> <br>
        <%= form.text_field :number %> <br><br>

        <%= label(:address,"Address")%> <br>
        <%= form.text_field :address %> <br><br>
        <%= form.submit "Save and Add", class: "button-class" %>


    <%end%>
</div>