rails-version/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "job#index", as: "root"
  get "/job-manager/:job_id", to: "job#job_manager", as: "manager"
  get "/job-manager/:job_id/candidate/:candidate_id", to: "job#job_manager", as: "candidate"

  get "/new-job", to: "job#new", as: "new_job"
  get "/new-candidate", to: "candidate#new", as: "new_candidate"

  post "/new-candidate", to: "candidate#create", as: "create_candidate"
  post "/new-job", to: "job#create", as: "create_job"

  get "/progress-candidate", to: "candidate#progress", as: "progress_candidate"
  get "/disqualify-candidate", to: "candidate#disqualify", as: "disqualify_candidate"
  get "/edit-candidate/:candidate_id", to: "candidate#edit", as: "edit_candidate"

  patch "/job-manager/:job_id/candidate/:candidate_id", to: "candidate#update"

  get "/new-note/candidate/:candidate_id", to: "note#new", as: "new_note"
  post "/new-note/candidate/:candidate_id", to: "note#create"

  get "/new-interview/candidate/:candidate_id", to: "interview#new", as: "new_interview"
  post "/new-interview/candidate/:candidate_id", to: "interview#create"

  get "/job-manager/:job_id/interviews", to: "interview#show", as: "interview_list"

  get "/complete-interview/candidate/:candidate_id", to: "interview#complete"
  patch "/complete-interview/candidate/:candidate_id", to: "interview#complete", as: "complete_interview"

  get "/reschedule-interview/candidate/:candidate_id", to: "interview#reschedule", as: "reschedule_interview"
  patch "/reschedule-interview/candidate/:candidate_id", to: "interview#update", as: "update_reschedule"


end

rails-version/app/controllers/interview_controller.rb
class InterviewController < ApplicationController
    def new
        @candidate = Candidate.find(params[:candidate_id])
        @job = Job.find(@candidate[:job_id])
    end

    def create
        @interview = Interview.new
        @interview.date = params[:date].in_time_zone('Australia/Brisbane')
        @interview.candidate_id = params[:candidate_id]
        @interview.job_id = params[:job_id]
        @interview.interviewer = params[:interviewer]
        @interview.status = "booked"
        @interview.comments = params[:comments]

        if @interview.valid? && @interview.save
            redirect_to candidate_path(:job_id => @interview[:job_id].to_i, :candidate_id => params[:candidate_id])
        else
            render "new"
        end
    end

    def show
        @job = Job.find(params[:job_id])
        @interviews = Interview.where(job_id: params[:job_id])
        @candidate_pool = Candidate.where(job_id: params[:job_id])
    end

    def complete
        @interview = Interview.where(candidate_id: params[:candidate_id])
        @interview.update(status: "completed")
        if @interview[0].valid? && @interview[0].save
            redirect_to interview_list_path(@interview[0][:job_id])
        else
            render "job_manager"
        end
    end

    def reschedule
        @interview = Interview.where(candidate_id: params[:candidate_id]).first
        @candidate = Candidate.find(@interview[:candidate_id])
    end

    def update
        @interview = Interview.where(candidate_id: params[:candidate_id]).first
        @interview.update(date: params[:interview][:date].in_time_zone('Australia/Brisbane'))

        if @interview.valid? && @interview.save
            redirect_to interview_list_path(@interview[:job_id])
        else
            render "reschedule"
        end
    end

    private
    def interview_params
        params.require(:interview).permit(:status, :date)
    end
end

rails-version/app/helpers/interview_helper.rb
module InterviewHelper
end

rails-version/app/views/interview/new.html.erb
<div class ="add-form">
    <h2> Schedule Interview | <%= "#{@candidate[:first_name]} #{@candidate[:last_name]}" %> </h2>
    <p> Please complete all fields </p>

    <%=form_with model:@interview, class: "form-class" do |form| %>
        <%= form.hidden_field :candidate_id, value: params[:candidate_id].to_i %>
        <%= form.hidden_field :job_id, value: @candidate[:job_id] %>
        <%= label(:date,"Date")%> <br>
        <%= form.datetime_field :date %> <br><br>

        <%= label(:interviewer,"Interviewer")%> <br>
        <%= form.text_field :interviewer %><br><br>

        <%= label(:comments,"Comments")%><br>
        <%= form.text_area :comments %> <br><br>
        <%= form.submit "Save and Add", class: "button-class" %>

    <%end%>
</div>

rails-version/app/views/interview/reschedule.html.erb
<div class ="add-form">
    <h3>Reschedule Interview | for <%= "#{@candidate[:first_name]} #{@candidate[:last_name]}"%> </h3>
    
    <%=form_with model:@interview, url: update_reschedule_path() do |form| %>

        <%= label(:date,"Select New Date")%> <br>
        <%= form.datetime_field :date %> <br><br>

        <%= form.submit "Save", class: "button-class" %>

    <%end%>

</div>

rails-version/app/views/interview/show.html.erb
<div class="job-details">
    <div class="job-title">
        <% if @job[:status] == "open"%>
            <div class="green-dot"></div>
        <% else%>
            <div class="red-dot"></div>
        <% end %>
        <h2> <%= "#{@job[:title]} | ##{@job[:id]}" %> </h2>
        <%= link_to manager_path(@job[:id]) do %> <div class="secondary-button" id="dashboard-button"> Dashboard </div> <% end %>
        <%= link_to interview_list_path(@job[:id]) do %>  <div class="secondary-button" id="interviews-button"> Interviews </div> <% end %>
    </div>
    <table>
        <tr>
            <td>Type: </td>
            <td> <%= @job[:work_type] %> </td>
            <td>Salary: </td>
            <td> <%= "$%.2f" % @job[:salary] %> </td>
        </tr>
        <tr>
            <td>Applications: </td>
            <td> <%= "%.0f" % @candidate_pool.length %> </td>
            <td>Start Date: </td>
            <td> <%= @job[:start_date] %> </td>
            <td>Reporting to: </td>
            <td> <%= @job[:reporting_to] %> </td>
        </tr>

    </table>
</div>


<div class="interview-log">
    <h2>Interview Log</h2>
    <% if @interviews.length == 0 %>
        <p> No interviews scheduled yet. </p>
    <% else %>
        <table>
            <tr>
                <th> Date </th>
                <th> Time </th>
                <th> Candidate </th>
                <th> Status</th>
                <th> Comments </th>
                <th> </th>
            </tr>
            <% for interview in @interviews%>
                <tr>
                    <td> <%= "#{DateFormat.change_to(interview[:date].in_time_zone('Australia/Brisbane'), "SHORT_DATE")}" %> </td>
                    <td> <%= "#{DateFormat.change_to(interview[:date].in_time_zone('Australia/Brisbane'), "MEDIUM_TIME")}" %> </td>
                    <td> <%= "#{Candidate.find(interview[:candidate_id]).first_name} #{Candidate.find(interview[:candidate_id]).last_name}"  %></td>
                    <td> <%= interview[:status] %></td>
                    <td> <%= interview[:comments] %></td>
                    <% if interview[:status] == "booked" %>
                        <td> 
                            <%= link_to complete_interview_path(interview[:candidate_id]) do %> <div class="secondary-button" id="complete"> Complete </div> <% end %>
                            <%= link_to reschedule_interview_path(interview[:candidate_id]) do %> <div class="secondary-button" id="reschedule"> Reschedule </div> <% end %>
                        </td>
                    <% end %>
                </tr>
                
            <% end %>
        </table>
    <% end %>

</div>