rails-version/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "job#index", as: "root"
  get "/job-manager/:job_id", to: "job#job_manager", as: "manager"
  get "/job-manager/:job_id/candidate/:candidate_id", to: "job#job_manager", as: "candidate"

  get "/new-job", to: "job#new", as: "new_job"
  get "/new-candidate", to: "candidate#new", as: "new_candidate"

  post "/new-candidate", to: "candidate#create", as: "create_candidate"
  post "/new-job", to: "job#create", as: "create_job"

  get "/progress-candidate", to: "candidate#progress", as: "progress_candidate"
  get "/disqualify-candidate", to: "candidate#disqualify", as: "disqualify_candidate"
  get "/edit-candidate/:candidate_id", to: "candidate#edit", as: "edit_candidate"

  patch "/job-manager/:job_id/candidate/:candidate_id", to: "candidate#update"

  get "/new-note/candidate/:candidate_id", to: "note#new", as: "new_note"
  post "/new-note/candidate/:candidate_id", to: "note#create"

  get "/new-interview/candidate/:candidate_id", to: "interview#new", as: "new_interview"
  post "/new-interview/candidate/:candidate_id", to: "interview#create"

  get "/job-manager/:job_id/interviews", to: "interview#show", as: "interview_list"

  get "/complete-interview/candidate/:candidate_id", to: "interview#complete"
  patch "/complete-interview/candidate/:candidate_id", to: "interview#complete", as: "complete_interview"

  get "/reschedule-interview/candidate/:candidate_id", to: "interview#reschedule", as: "reschedule_interview"
  patch "/reschedule-interview/candidate/:candidate_id", to: "interview#update", as: "update_reschedule"


end

rails-version/app/views/layouts/application.html.erb
<html>
    <head>
        <title>railsHRM</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <link rel="stylesheet" href="job.css">
        <script src="https://kit.fontawesome.com/9828386ba7.js" crossorigin="anonymous"></script>

    </head>

    <body>
        <%= render "shared/sidebar"%>
        <div class="content" >
            <div class="top-function-bar">
                <div class="main-button"> <%= link_to new_job_path() do %> <span>Add Job </span> <% end %> </div> 
                <div class="main-button"> <%= link_to new_candidate_path() do %> <span> Add Candidate </span> <% end %> </div> 
            </div>
            <%= yield %>
        </div>
    </body>

</html>

rails-version/app/views/layouts/job_manager.html.erb
<html>
    <head>
        <title>railsHRM</title>
        <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <link rel="stylesheet" href="job.css">
        <script src="https://kit.fontawesome.com/9828386ba7.js" crossorigin="anonymous"></script>

    </head>

    <body>
        <%= render "shared/sidebar"%>

        <div class="content" >

            <div class="top-function-bar">
                <div class="main-button"> <%= link_to new_job_path() do %> <span>Add Job </span> <% end %> </div> 
                <div class="main-button"> <%= link_to new_candidate_path() do %> <span> Add Candidate </span> <% end %> </div> 
                <div class="main-button">Interview Log</div>
            </div>
             
            <%= yield %>

        </div>


    </body>

</html>