rails-version/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/", to: "job#index", as: "root"
  get "/job-manager/:job_id", to: "job#job_manager", as: "manager"
  get "/job-manager/:job_id/candidate/:candidate_id", to: "job#job_manager", as: "candidate"

  get "/new-job", to: "job#new", as: "new_job"
  get "/new-candidate", to: "candidate#new", as: "new_candidate"

  post "/new-candidate", to: "candidate#create", as: "create_candidate"
  post "/new-job", to: "job#create", as: "create_job"

  get "/progress-candidate", to: "candidate#progress", as: "progress_candidate"
  get "/disqualify-candidate", to: "candidate#disqualify", as: "disqualify_candidate"
  get "/edit-candidate/:candidate_id", to: "candidate#edit", as: "edit_candidate"

  patch "/job-manager/:job_id/candidate/:candidate_id", to: "candidate#update"

  get "/new-note/candidate/:candidate_id", to: "note#new", as: "new_note"
  post "/new-note/candidate/:candidate_id", to: "note#create"

  get "/new-interview/candidate/:candidate_id", to: "interview#new", as: "new_interview"
  post "/new-interview/candidate/:candidate_id", to: "interview#create"

  get "/job-manager/:job_id/interviews", to: "interview#show", as: "interview_list"

  get "/complete-interview/candidate/:candidate_id", to: "interview#complete"
  patch "/complete-interview/candidate/:candidate_id", to: "interview#complete", as: "complete_interview"

  get "/reschedule-interview/candidate/:candidate_id", to: "interview#reschedule", as: "reschedule_interview"
  patch "/reschedule-interview/candidate/:candidate_id", to: "interview#update", as: "update_reschedule"


end

rails-version/app/models/job.rb
class Job < ApplicationRecord
end

rails-version/app/controllers/job_controller.rb
require 'date_format'

class JobController < ApplicationController
    skip_before_action :verify_authenticity_token
    before_action :setup_jobs
    attr_reader :candidate

    def index
    end

    def new
        @job = Job.new
    end

    def create
        @job = Job.new(job_params)
        @job.status = "open"

        if @job.valid? && @job.save
            redirect_to manager_path(@job[:id])
        else
            render "new"
        end
    end

    def job_manager
        @job = @jobs.find(params[:job_id])
        @candidate_pool = @candidates.where(job_id: params[:job_id])

        @columns = { "applied" => 0, "contacted" => 1, "screened" => 2, "shortlisted" => 3, "interview" => 4, "offer" => 5, "accepted" => 6, "disqualified" => 7}
        @repeats = Hash.new(0)

        if @candidate_pool != []
            @candidate_pool.each do | candidate |
                if candidate[:id] == params[:id].to_i
                    @candidate = candidate
                else
                    @error = "Error: non-existent candidate"
                end

                @repeats[candidate[:status].downcase] += 1
            end
        
            @row_count = @repeats.values.max
            @row_data = []

            until @row_count == 0 
                @row_data.push(["", "", "", "", "", "", "", ""])
                @row_count -= 1
            end
        end

        @candidate = @candidates.where(id: params[:candidate_id]).first

        if @candidate
            @notes = Note.where(candidate_id: @candidate[:id]).reverse
            @interviews = Interview.where(candidate_id: @candidate[:id]).reverse
        end

        @prog_error = params[:prog_error]

    end

    
    private
    def setup_jobs
        @jobs = Job.all
        @candidates = Candidate.all
    end

    def job_params
        params.require(:job).permit(:title, :work_type, :salary, :openings, :start_date, :reporting_to, :status)
    end

end

rails-version/app/helpers/job_helper.rb
module JobHelper
end

rails-version/app/views/job/index.html.erb
<div class="job-list-display">
    <h1> Joblist</h1>
    <% if @jobs.length == 0 %>
        <p> Start recruiting now! Hit the "Add Job" button at top right corner. <p>
    <% else %>
        <% @jobs.each do | job | %>
            <%= link_to manager_path(job[:id]) do %>
                <div class="details-panel">
                    <p> <%= job[:id] %> </p>
                    <p> <%= job[:title] %> </p>
                    <p> <%= job[:work_type] %> </p>
                    <p> <%= "$%.2f" % job[:salary] %> </p>
                    <p> <%= "%.0f" % job[:openings] %> </p>
                    <p> <%= job[:start_date] %> </p>
                    <p> <%= job[:reporting_to] %> </p>
                    <% if job[:status] == "open" %>
                        <div class="green-dot"></div>
                    <% else %>
                        <div class="red-dot"></div>
                    <% end %>
                </div>
            <% end %>
        <% end %>
    <% end %>
    
</div>

rails-version/app/views/job/job_manager.html.erb
<div class="job-details">
    <div class="job-title">
        <% if @job[:status] == "open"%>
            <div class="green-dot"></div>
        <% else%>
            <div class="red-dot"></div>
        <% end %>
        <h2> <%= "#{@job[:title]} | ##{@job[:id]}" %> </h2>
        <%= link_to manager_path(@job[:id]) do %> <div class="secondary-button" id="dashboard-button"> Dashboard </div> <% end %>
        <%= link_to interview_list_path(@job[:id]) do %>  <div class="secondary-button" id="interviews-button"> Interviews </div> <% end %>
    </div>

    <table>
        <tr>
            <td>Type: </td>
            <td> <%= @job[:work_type] %> </td>
            <td>Salary: </td>
            <td> <%= "$%.2f" % @job[:salary] %> </td>
        </tr>
        <tr>
            <td>Applications: </td>
            <td> <%= "%.0f" % @candidate_pool.length %> </td>
            <td>Start Date: </td>
            <td> <%= @job[:start_date] %> </td>
            <td>Reporting to: </td>
            <td> <%= @job[:reporting_to] %> </td>
        </tr>
    </table>


</div>

<div class="dashboard-title"> <h2>Dashboard</h2> </div>

<% if @candidate_pool != [] %>
    <div class="progression-table">
        <table>
            <thead>
                <tr>
                    <th>Applied (<%= @repeats["applied"] %>) </th>
                    <th>Contacted (<%= @repeats["contacted"] %>) </th>
                    <th>Screened (<%= @repeats["screened"] %>) </th>
                    <th>Shortlisted (<%= @repeats["shortlisted"] %>) </th>
                    <th>Interview (<%= @repeats["interview"] %>) </th>
                    <th>Offer (<%= @repeats["offer"] %>) </th>
                    <th>Accepted (<%= @repeats["accepted"] %>) </th>
                    <th>Disqualified (<%= @repeats["disqualified"] %>) </th>
                </tr>
            </thead>

            <% @candidate_pool.each do | candidate | %>
                <% if @repeats[candidate[:status].downcase] > 0%>
                    <% @row_data[@repeats[candidate[:status].downcase]-1][@columns[candidate[:status].downcase]] = candidate %>
                    <% @repeats[candidate[:status].downcase] -= 1%>
                <% end %>
            <% end %>

            <% @row_data.each do | row | %>
                <tr>
                    <% row.each do | candidate | %>
                        <% if candidate != "" %>
                            <td class="taken">  <%= link_to "#{candidate[:first_name]} #{candidate[:last_name]}", candidate_path(:candidate_id => candidate[:id]) %> </td>                      
                        <% else %>
                            <td> </td>
                        <% end %>
                    <% end %>
                </tr>

            <% end %>  

        </table>

    </div>
<% else %>
    <div class="progression-table">
        <table>
            <thead>
                <tr>
                    <th>Applied (0) </th>
                    <th>Contacted (0) </th>
                    <th>Screened (0) </th>
                    <th>Shortlisted (0) </th>
                    <th>Interview (0) </th>
                    <th>Offer (0) </th>
                    <th>Accepted (0) </th>
                    <th>Disqualified (0) </th>
                </tr>
            </thead>

        </table>


    </div>

    <p id="add-prompt"> Start recruiting for this role now! </p>

<% end %>

<% if @candidate %>

    <div class="candidate-display">
        <% if @prog_error %>
            <p class="progression-error"> <%= @prog_error %> </p>
        <% end %>

        <h2> <%= "Profile | #{@candidate[:first_name]} #{@candidate[:last_name]}" %> </h2>
        <div class="candidate-action-bar">
            <div class="secondary-button"> <%= link_to progress_candidate_path(:candidate_id => @candidate[:id]) do %> Progress <% end %> </div>
            <div class="secondary-button"> <%= link_to disqualify_candidate_path(:candidate_id => @candidate[:id]) do %>  Disqualify <% end %> </div>
            <div class="secondary-button"> <%= link_to new_interview_path(:candidate_id => @candidate[:id]) do %>  Schedule Interview <% end %> </div>
            <div class="secondary-button"> <%= link_to new_note_path(:candidate_id => @candidate[:id]) do %>  Make Note <% end %> </div>
        </div>
        <div class="details-box">
            <div class="main-details">
                <h3> Details </h3>
                <table>
                    <tr>
                        <td>Status:</td>
                        <td> <%= @candidate[:status].capitalize %> </td>
                    </tr>
                    <tr>
                        <td>Occupation:</td>
                        <td> <%= @candidate[:occupation] %> </td>
                    </tr>
                    <tr>
                        <td>Email:</td>
                        <td> <%= @candidate[:email] %> </td>
                    </tr>
                    <tr>
                        <td>Number:</td>
                        <td> <%= @candidate[:number] %> </td>
                    </tr>
                    <tr>
                        <td>Address:</td>
                        <td> <%= @candidate[:address] %> </td>
                    </tr>
                </table>
                <div class="secondary-button"> <%= link_to edit_candidate_path(:candidate_id => @candidate[:id], :job_id => @job[:id]) do %>  Edit <% end %> </div>
            </div>
            <% if @interviews.length > 0 %>
                <div class="interviews-details">
                    <h3> Next Interview </h3>
                    <div class="interview-display">
                        <div class="interview-box">
                            <h4 class="comment-text"> <%= @interviews[0][:comments] %></h4>
                            <p> Date: <%= "#{DateFormat.change_to(@interviews[0][:date].in_time_zone('Australia/Brisbane'), "MEDIUM_DATE")}" %> </p>
                            <p> Time: <%= "#{DateFormat.change_to(@interviews[0][:date].in_time_zone('Australia/Brisbane'), "MEDIUM_TIME")}" %> </p>
                            <p class="comment-text"> Status: <%= @interviews[0][:status] %></p>
                        </div>                        
                    </div>
                </div>
            <% end %>
            <% if @notes.length > 0 %>
                <div class="note-details">
                    <h3> Notes </h3>
                    <div class="notes-display">
                        <% for note in @notes %>
                            <div class="note-box">
                                <p class="timestamp"> <%= "#{DateFormat.change_to(note[:created_at].in_time_zone('Australia/Brisbane'), "MEDIUM_DATE")} | #{DateFormat.change_to(note[:created_at].in_time_zone('Australia/Brisbane'), "MEDIUM_TIME")}" %> </p>
                                <p class="note-text"> <%= note[:note] %></p>
                            </div>                        
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>

    </div>
<% end %>

rails-version/app/views/job/new.html.erb
<div class ="add-form">
    <h1> Add Job </h1>
    <p> Please complete all fields </p>

    <%= form_with model: @job, url: create_job_path() do |form| %>
        <%= label(:title,"Job Title")%> <br>
        <%= form.text_field :title %> <br><br>

        <%= label(:work_type,"Type")%> <br>
        <%= form.select(:work_type, ['Full Time', 'Part Time', 'Casual', 'Fixed Term'] )  %><br><br>

        <%= label(:salary,"Salary")%><br>
        <%= form.number_field :salary %> <br><br>

        <%= label(:openings,"# of Openings")%><br>
        <%= form.number_field :openings, value: 1 %> <br><br>

        <%= label(:start_date,"Start Date")%> <br>
        <%= form.date_field :start_date %> <br><br>

        <%= label(:reporting_to,"Reporting To")%> <br>
        <%= form.text_field :reporting_to %> <br><br>

        <%= label(:description,"Job Description")%> <br>
        <%= form.text_area :description %> <br><br>
        <%= form.submit "Save and Add", class: "button-class" %>


    <%end%>
</div>